// sim/llm.mjs — the ONLY thing in sim/ that talks to a model.
//
// WHY A REAL MODEL AND NOT A FIXTURE. A persona is only a persona if its output
// is produced the way a real bot's output is produced. A hand-written
// "chatty" block is a hypothesis about what chatty looks like, and testing the
// library against your own hypothesis cannot fail in the direction that matters.
// So every persona's memory block is GENERATED by an actual model on the host,
// over a real task, through the same Ollama endpoint a deployment would use.
//
// That makes Ollama a HARD dependency of the persona suites, which is the point
// of the card's "must not quietly degrade to green" rule: with no model there
// are no personas, and a harness that reports green without having produced any
// output is worse than no harness at all.

const DEFAULT_HOST = process.env.SIM_OLLAMA_HOST || 'http://host.docker.internal:11434';
const DEFAULT_MODEL = process.env.SIM_MODEL || 'qwen2.5-coder:14b';
const JUDGE_MODEL = process.env.SIM_JUDGE_MODEL || DEFAULT_MODEL;

// One request's worth of wall clock. A 14B on Apple silicon answers a
// 500-token block in tens of seconds; 240s is generous but still bounded, so a
// wedged server surfaces as a TIMEOUT with a name instead of a hung harness.
const REQUEST_TIMEOUT_MS = Number(process.env.SIM_REQUEST_TIMEOUT_MS || 240_000);

export function ollamaHost() { return DEFAULT_HOST.replace(/\/+$/, ''); }
export function model() { return DEFAULT_MODEL; }

// Distinguishes the four ways the model endpoint can be unusable, because the
// operator's fix is different for each and a generic "connection failed" sends
// them to the wrong one.
function classifyFetchError(e) {
  const msg = String(e?.message || e);
  const cause = String(e?.cause?.code || e?.cause?.message || '');
  if (e?.name === 'TimeoutError' || /timed? ?out/i.test(msg)) {
    return `Ollama accepted the connection but did not answer within ${REQUEST_TIMEOUT_MS}ms. `
      + 'The model may be cold-loading, or the host may be under GPU pressure. '
      + `Check: curl ${ollamaHost()}/api/ps  — and raise SIM_REQUEST_TIMEOUT_MS if a cold load is expected.`;
  }
  if (/ECONNREFUSED/.test(cause) || /ECONNREFUSED/.test(msg)) {
    return `Nothing is listening on ${ollamaHost()}. From the HOST the address is normally `
      + 'http://localhost:11434 — host.docker.internal only exists inside the container. '
      + 'Start it with: ollama serve';
  }
  if (/ENOTFOUND|EAI_AGAIN|getaddrinfo/.test(cause) || /ENOTFOUND/.test(msg)) {
    return `Cannot resolve "${new URL(DEFAULT_HOST).hostname}". Inside the container that name is `
      + 'supplied by --add-host=host.docker.internal:host-gateway; if you ran the harness '
      + 'outside Docker, export SIM_OLLAMA_HOST=http://localhost:11434 instead.';
  }
  if (/ECONNRESET|EPIPE|socket hang up/i.test(msg)) {
    return `The connection to ${ollamaHost()} was reset mid-request. A model server that OOMs on a `
      + 'large prompt does this; lower the persona token budget or unload other models first.';
  }
  return `Unclassified failure talking to ${ollamaHost()}: ${msg}`;
}

export class OllamaUnreachable extends Error {
  constructor(detail, hint) {
    super(`SIM: BLOCKED — the simulation cannot run without a model.\n\n  ${detail}\n\n  ${hint}`);
    this.name = 'OllamaUnreachable';
  }
}

// Preflight. Called BEFORE any suite runs so an unreachable model is a loud,
// named failure with the fix in the message — not six silent "0 personas"
// entries and a green verdict line.
export async function preflight() {
  const started = Date.now();
  const base = ollamaHost();
  let tags;
  try {
    const res = await fetch(`${base}/api/tags`, { signal: AbortSignal.timeout(15_000) });
    if (!res.ok) throw new Error(`${base}/api/tags returned HTTP ${res.status}`);
    tags = await res.json();
  } catch (e) {
    throw new OllamaUnreachable(
      `Cannot reach Ollama at ${base} — ${e.message}`,
      classifyFetchError(e));
  }
  const installed = (tags.models || []).map(m => m.name);
  if (!installed.includes(DEFAULT_MODEL)) {
    throw new OllamaUnreachable(
      `Ollama is up at ${base} but does not have "${DEFAULT_MODEL}". Installed: ${installed.join(', ') || '(none)'}`,
      `Pull it with: ollama pull ${DEFAULT_MODEL}   (or point the harness at another one with SIM_MODEL=…)`);
  }
  return {
    host: base,
    model: DEFAULT_MODEL,
    judgeModel: JUDGE_MODEL,
    installed,
    latencyMs: Date.now() - started,
    node: process.version,
    platform: `${process.platform}/${process.arch}`,
  };
}

async function chat(modelName, messages, { numPredict = 700, temperature = 0.8, format } = {}) {
  const body = {
    model: modelName,
    messages,
    stream: false,
    options: { num_predict: numPredict, temperature },
  };
  if (format) body.format = format;
  let res;
  try {
    res = await fetch(`${ollamaHost()}/api/chat`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    });
  } catch (e) {
    throw new OllamaUnreachable(`chat(${modelName}) failed — ${e.message}`, classifyFetchError(e));
  }
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new OllamaUnreachable(
      `chat(${modelName}) returned HTTP ${res.status}: ${body.slice(0, 400)}`,
      res.status === 404
        ? `The server is up but has no model named "${modelName}". ollama pull ${modelName}`
        : 'Check `ollama serve` logs — a 500 here is usually a crashed model or a full disk.');
  }
  const json = await res.json();
  return (json.message?.content || '').trim();
}

// Deterministic JSON answer from the judge model, with one bounded retry.
// A judge that answers in prose would need prose parsing, and prose parsing of
// an LLM verdict is a second source of wrong answers.
async function chatJson(modelName, messages, opts = {}) {
  for (let attempt = 1; attempt <= 2; attempt++) {
    const raw = await chat(modelName, messages, { ...opts, format: 'json' });
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === 'object') return parsed;
    } catch { /* fall through to retry */ }
    if (attempt === 2) {
      throw new Error(`judge(${modelName}) did not return JSON after 2 attempts: ${raw.slice(0, 300)}`);
    }
  }
  throw new Error('unreachable');
}

export function generate({ system, prompt, numPredict = 700, temperature = 0.8 }) {
  return chat(DEFAULT_MODEL, [{ role: 'system', content: system }, { role: 'user', content: prompt }],
    { numPredict, temperature });
}

export function judge({ system, prompt, numPredict = 900 }) {
  return chatJson(JUDGE_MODEL, [{ role: 'system', content: system }, { role: 'user', content: prompt }],
    { numPredict, temperature: 0 });
}
