// sim/personas.mjs — six bot personas, each with a genuinely different
// memory-writing style, each GENERATED BY A REAL MODEL over a real task.
//
// WHY STYLES AND NOT SIZES. The library's promotion gate counts SESSIONS and
// DOMAINS. Uniform personas all cross that gate on the same inputs, so a uniform
// suite measures one point in the space and calls it coverage. The styles below
// are chosen to attack different parts of the pipeline:
//
//   chatty       → parses fine, promotes fine, but floods: does the merge
//                  survive volume, and do near-duplicate names fragment?
//   terse        → parses fine, promotes almost nothing: is the *useful* one
//                  getting lost in the noise, or is recall genuinely empty?
//   noisy        → claims that are status chatter; does assessClaim reject the
//                  narration without eating the one real claim beside it?
//   degenerate   → structurally broken: prototype-key headers, 1MB blocks,
//                  fences-in-fences, unicode edges. Must not throw, must not
//                  hang, must not pollute Object.prototype.
//   hostile      → the exact inputs that broke the real deployment, isolated so
//                  a failure names its trigger instead of "degenerate".
//   knowledgeable→ MUST survive. If genuinely useful cross-domain claims do not
//                  promote, the filter is too aggressive and that is the most
//                  expensive possible bug.
//
// TOPIC POOL. Real content — agent orchestration, security findings, deploy
// practice, memory architecture, Josh's actual decisions. Lorem ipsum cannot
// surface a relevance bug, and a relevance bug is the one this whole card
// exists to catch.
//
// FOUR SESSIONS PER PERSONA. promotion's established bar is 3+ sessions AND 2+
// domains (computeStatus). Three sessions would sit exactly on the boundary, so
// four: three to cross it, one to prove the union is stable on replay.

export const SESSION_DATES = ['2026-10-11', '2026-10-12', '2026-10-13', '2026-10-14'];

// Realistic, dated, specific. Nothing here is invented filler: these are the
// kinds of things Josh's fleet actually decided, which is what makes a
// promotion the *wrong* thing detectable.
export const TOPIC_POOL = [
  {
    id: 'atomic-rename',
    task: 'Audit the memory index write path for torn-file risk on crash, and tell Josh whether the write is atomic.',
    domain: 'ops',
  },
  {
    id: 'launchd-token',
    task: 'Two launchd plists on Josh\'s Mac Mini both claimed the Telegram bot token and restarted each other in a loop. Diagnose it.',
    domain: 'ops',
  },
  {
    id: 'session-traversal',
    task: 'Explain why a session date like "../../../../TARGET.json" was an arbitrary-path primitive, and what the real fix was.',
    domain: 'code',
  },
  {
    id: 'two-tier-design',
    task: 'Justify Polymem\'s two-tier design: session working memory plus an evidence-gated patterns index. When is one tier enough?',
    domain: 'code',
  },
  {
    id: 'prototype-safety',
    task: 'A model emitted "### constructor" as a memory section header. Explain exactly why that crashed the parser and what the structural fix was.',
    domain: 'code',
  },
  {
    id: 'evidence-gate',
    task: 'Why is promotion gated on 2+ sessions AND 2+ domains rather than on a single confident statement? Give the concrete failure it prevents.',
    domain: 'research',
  },
  {
    id: 'disk-headroom',
    task: 'Disk hit 87% before the last purge. What cleared it, what was deliberately left, and what would you automate next time?',
    domain: 'ops',
  },
  {
    id: 'gateway-restart',
    task: 'Explain the fix for the gateway restart loop where the default and chief launchd agents fought over one token.',
    domain: 'ops',
  },
  {
    id: 'signal-filter',
    task: 'A memory corpus filled up with an LLM grading its own word counts. Describe the negative-only claim filter that keeps that out without judging good claims.',
    domain: 'research',
  },
  {
    id: 'scope-discipline',
    task: 'A card asked for a fix and the agent also refactored the test suite. State Josh\'s rule about scope, and the one exception he grants.',
    domain: 'other',
  },
  {
    id: 'verify-then-ship',
    task: 'What does "verify, then ship" mean operationally here, and what happened the last time a doc claimed a feature was production-ready when only a note said so?',
    domain: 'other',
  },
  {
    id: 'embeddings-honesty',
    task: 'Why does queryPatterns do literal substring matching instead of embedding similarity, and under what corpus is that the wrong choice?',
    domain: 'research',
  },
];

// The contract, stated once. A persona prompt that omits it produces blocks the
// parser legitimately rejects, and then the simulation measures the prompt.
export const FENCE_CONTRACT = `
End your reply with EXACTLY ONE fenced block that begins with \`\`\`memory on its own line.

Its body uses these section headers, each on its own line, each starting with three hashes and a space:
### Claims        (a bullet is one durable fact you learned, not a narration of what you just did)
### Patterns      (a bullet is a reusable technique or rule, named as a short noun phrase)
### Correspondences  (a bullet states how two named things correspond, using "↔")
### Contradictions (a bullet states something that CONTRADICTS an earlier belief)

Every bullet starts with "- " and is on ONE line, under 300 characters.
A bullet in Claims or Patterns may end with " — domains: code" (or research, design, ops, finance, comms, other), comma-separated.
Write between 3 and 8 bullets per section. Do not write a section you have nothing for.
Do not put text after the closing fence.
`.trim();

// ── Persona prompts ─────────────────────────────────────────────────────────
//
// Each system prompt is a WRITING STYLE, not a personality. The point is what
// lands in the memory fence, not how charming the display text is.

const BASE = `You are a background bot agent in Josh Watson's Omega fleet. You do real infrastructure, security and memory-architecture work. ${FENCE_CONTRACT}

Write the way THIS kind of bot writes, not the way a textbook would.`;

export const PERSONAS = [
  {
    id: 'chatty',
    label: 'Chatty',
    writesStyle: 'long blocks that restate the task, repeat themselves, and explain their reasoning in the bullet text itself',
    expect: 'mostly recoverable claims; the risk is volume and near-duplicate fragmentation, not rejection',
    system: `${BASE}

YOUR STYLE: chatty and thorough. You restate the task in your answer before answering it. In the memory block you write LONG bullets that repeat earlier bullets in different words, explain your reasoning inside the bullet, and hedge ("I believe", "it seems", "this should"). You name the same technique several ways across sections. You are not being malicious, you are being verbose.`,
  },
  {
    id: 'terse',
    label: 'Terse',
    writesStyle: 'one-line bullets, often too vague to be useful later, minimal domains',
    expect: 'almost nothing promotes; the one genuinely useful bullet may be lost among the vague ones',
    system: `${BASE}

YOUR STYLE: terse to the point of uselessness. One-line bullets. You rarely say which domains something belongs to. You write things like "fixed it" or "the usual fix applies" or "same as before" without saying what the fix IS. You are not being lazy, you are being brief because brevity is what you optimise for.`,
  },
  {
    id: 'noisy',
    label: 'Noisy',
    writesStyle: 'greetings, status chatter, emoji, markdown noise mixed with a small amount of real content',
    expect: 'narration ("running tests…", "user requested…") must be rejected while the one real claim survives',
    system: `${BASE}

YOUR STYLE: noisy. Your reply opens with a greeting and a progress report ("hey! running tests now… 🚀"). The memory block is full of status chatter, emoji, markdown bold/italics noise, horizontal rules, and self-report about your own output ("I responded with 42 words", "this should have been 5 words"). MOST of what you write is narration of the moment. Bury ONE or TWO genuinely useful, durable facts somewhere in it.`,
  },
  {
    id: 'degenerate',
    label: 'Degenerate',
    writesStyle: 'structurally broken memory blocks — wrong headers, prototype-key names, empty sections, code fences, unicode edges, huge bullets',
    expect: 'no throw, no hang, no prototype pollution, no lost index — degradation is fine, a crash is not',
    system: `${BASE}

YOUR STYLE: degenerate. You are emitting a structurally broken memory block and you do not know it. Do ALL of the following across your reply, as a model that has lost the plot would:
- Use at least one section header that is NOT one of the four, including the literal words "### constructor" and "### __proto__".
- Include an empty section with no bullets.
- Include a bullet that is a single line of more than 2000 characters with no spaces.
- Nest a \`\`\` fence inside your memory block.
- Include unicode edge cases: a zero-width joiner, a right-to-left override, a combining acute accent, and an emoji ZWJ sequence.
Write real content too — the breakage is structural, not semantic.`,
  },
  {
    id: 'knowledgeable',
    label: 'Knowledgeable',
    writesStyle: 'precise, durable, cross-domain claims that name the mechanism and the consequence',
    expect: 'THIS IS THE ONE THAT MUST SURVIVE. If these do not promote and reach established, the filter is too aggressive.',
    system: `${BASE}

YOUR STYLE: knowledgeable and precise. Every bullet names a MECHANISM and a CONSEQUENCE, not an activity. You always tag domains, and you deliberately reach across at least two domains (for example a code fact that has an ops consequence). You state what is true about the system, not what you did in the last ten minutes. You never narrate your own output quality and never log requests or events. You repeat nothing.`,
  },
];

// The hostile set, kept as its own persona so a failure names its exact trigger.
// Each entry is a deterministic mutation applied to a well-formed block — the
// point is to isolate which structural element breaks the parser.
export const HOSTILE_CASES = [
  {
    id: 'constructor-header',
    desc: '### constructor as a section header (the real deployment\'s crash)',
    apply: (b) => b.replace('### Claims', '### constructor\n- x\n### Claims'),
  },
  {
    id: 'proto-header',
    desc: '### __proto__ as a section header',
    apply: (b) => b.replace('### Claims', '### __proto__\n- x\n### Claims'),
  },
  {
    id: 'prototype-sweep',
    desc: 'every Object.prototype member name used as a section header',
    apply: (b) => b.replace('### Claims',
      '### toString\n- x\n### valueOf\n- x\n### hasOwnProperty\n- x\n### isPrototypeOf\n- x\n### propertyIsEnumerable\n- x\n### toLocaleString\n- x\n### __defineGetter__\n- x\n### __lookupSetter__\n- x\n### Claims'),
  },
  {
    id: 'proto-pattern-name',
    desc: 'a pattern named "constructor" and one named "__proto__"',
    apply: (b) => `${b}\n- __proto__\n- constructor\n`,
  },
  {
    id: 'one-mb-block',
    desc: 'a 1MB memory block (a single huge bullet)',
    apply: (b) => `${b}\n- ${'A'.repeat(1024 * 1024)}\n`,
  },
  {
    id: 'no-sections',
    desc: 'a well-formed fence containing prose and no section headers at all',
    apply: () => '```memory\njust some prose, no headers here\n```',
  },
  {
    id: 'empty-fence',
    desc: 'an opening fence with no body and no closing fence',
    apply: () => '```memory\n',
  },
  {
    id: 'five-thousand-lines',
    desc: '5,000 bullet lines in one section (MAX_LINES_PER_SECTION is 20)',
    apply: (b) => b + '\n' + Array.from({ length: 5000 }, (_, i) => `- filler bullet number ${i}`).join('\n'),
  },
  {
    id: 'fence-in-fence',
    desc: 'a nested ``` fence inside the memory block',
    apply: (b) => b.replace('### Claims', '```js\nconst x = 1;\n```\n### Claims'),
  },
  {
    id: 'unicode-edges',
    desc: 'zero-width joiner, RTL override, combining accent, ZWJ emoji, lone surrogate',
    apply: (b) => b + '\n- zwj:\u200d rtl:\u202e acuted:e\u0301 zwj-emoji:\u{1F468}\u200D\u{1F469}\u200D\u{1F467} lone-surrogate:\uD800 end\n',
  },
  {
    id: 'prototype-polluted-json',
    desc: 'an index file whose patterns object carries a literal __proto__ key',
    onDisk: true,
  },
  {
    id: 'bullet-length-boundary',
    desc: 'bullets around the 300-char drop threshold and the 200-char truncation',
    // FOUND BY THE PERSONAS, not designed in. The chatty persona produced a
    // valid fence on all four dates and yielded ZERO bullets every time, while
    // every other persona parsed fine. The cause is polymem.mjs:1164:
    //   if (!item || item.length > 300) continue;    // >300 -> DROPPED entirely
    //   ... memory[current].push({ text: item.slice(0, 200), ... })  // else -> cut to 200
    //
    // So the two length rules disagree at the boundary. A 350-char bullet
    // vanishes with no trace; a 250-char bullet is kept and truncated. Verbose
    // writers therefore lose 100% of their memory while terse writers lose
    // nothing, and neither the README nor the JSDoc mentions either threshold.
    //
    // This case pins the behaviour so it is a measurement rather than an
    // anecdote, and so a future change to the threshold shows up as a diff here
    // instead of as a quiet change in what gets remembered.
    bulletLengths: [50, 199, 200, 201, 299, 300, 301, 400, 1200],
  },

  {
    id: 'header-placement',
    desc: 'section headers in shapes a model plausibly emits',
    // FOUND BY THE PERSONAS. The chatty persona wrote a valid fence on 3 of 4
    // dates and every bullet was discarded. The first diagnosis blamed the
    // 300-char bullet threshold — the measurement disproved it (longest bullet was
    // 174 chars). Isolating the parser showed THREE distinct shapes that each
    // yield zero claims while still returning a well-formed memory object:
    //
    //   1. no '###' header at all        -> every bullet skipped (current = null)
    //   2. '###' indented off line-start -> header never matches, same result
    //   3. '### Claims' glued to a bullet -> the bullet is consumed as part of the
    //      header line, so nothing follows it
    //
    // All three return { claims: [], patterns: [], ... } — not null, not a throw.
    // A caller cannot tell any of them from "this bot had nothing to say". This
    // case pins the behaviour so a future fix to the header matcher shows up as
    // a diff here instead of as a quiet change in what gets remembered.
    headerShapes: [
      { name: 'canonical', text: '### Claims\n- alpha claim\n### Patterns\n- alpha pattern' },
      { name: 'no-headers', text: '- alpha claim\n- alpha pattern' },
      { name: 'indented-header', text: '  ### Claims\n- alpha claim\n  ### Patterns\n- alpha pattern' },
      { name: 'header-and-bullet-same-line', text: '### Claims- alpha claim' },
      { name: 'bullet-then-header', text: '- alpha claim\n### Patterns\n- alpha pattern' },
      { name: 'unknown-section', text: '### Musings\n- alpha claim' },
      { name: 'lowercase-header', text: '### claims\n- alpha claim' },
      { name: 'crlf', text: '### Claims\r\n- alpha claim' },
    ],
  },

  {
    id: 'date-traversal',
    desc: 'session dates that try to escape the sessions directory — all MUST be refused',
    // Grouped by EXPECTED OUTCOME, because these are not one class of test.
    //
    // CONTAINMENT strings are a correctness requirement: a path separator in a
    // session key means an arbitrary-path primitive, and refusing one is right.
    // The format guard at polymem.mjs:1215 closes this structurally, so these
    // are expected to be rejected and any acceptance is a BLOCKER.
    //
    // CALENDAR strings are a much smaller matter and are graded separately.
    // "2026-13-45" matches /^\d{4}-\d{2}-\d{2}$/ perfectly well, so the library
    // accepts it and files the session under working-2026-13-45.json. That is
    // cosmetic — it cannot escape containment, it just creates a file named
    // after a date that does not exist. Charging it as a containment failure
    // would overstate it, and a harness that overstates findings trains its
    // reader to discount the list.
    dates: {
      mustReject: ['../../../../TMP_CANARY_ABC', '../../../TMP_CANARY_ABC',
        '/etc/passwd', '2026-10-11/../../TMP_CANARY_ABC', '..', '.',
        '', 'null', 'undefined', '2026-1-1', '...', '2026-10-11\\x', '../'.repeat(9) + 'TARGET'],
      mayAccept: ['2026-13-45', '2026-02-30', '9999-99-99', '0000-00-00'],
    },
    onDisk: true,
  },
  {
    id: 'non-string-input',
    desc: 'null / undefined / number / object / array passed where a block is expected',
    nonString: [null, undefined, 0, 42, {}, [], ['- a'], { claims: ['x'] }],
    onDisk: true,
  },
  {
    id: 'junk-sections',
    desc: 'non-object bullets, 5000 domains on one pattern, duplicate and empty domains',
    junkEntry: true,
    onDisk: true,
  },
];

// Build the prompt for one persona on one session.
//
// WHY THE CONTRACT IS RESTATED AT THE END. Measured on this host with
// qwen2.5-coder:14b: with the fence contract only in the system prompt, roughly
// 2 in 6 replies contained no ```memory fence at all — the model wrote the
// section headers as bare prose, or ran out of tokens mid-block. That is a
// HARNESS defect, not a library defect: parseMemoryBlock correctly returned
// { memory: null }, and counting that as a Polymem bug would have been wrong.
//
// The honest fix is to make the harness ask reliably, not to count the misses as
// findings. The contract is restated as the LAST thing in the user turn (recency
// is what actually governs instruction-following at this size) and the token
// budget is raised, since a truncated block is indistinguishable from a model
// that declined to write one. The residual miss rate is still measured and
// reported, because a persona that never produces a fence is a fact about the
// model that an operator should see.
export function personaPrompt(persona, topic, date) {
  return [
    `Session date: ${date}`,
    `Your task: ${topic.task}`,
    '',
    'Reply the way you always reply: your normal prose reply first, then your memory block.',
    '',
    'Reminder — your reply MUST end with a fenced block whose first line is exactly ```memory,',
    'using the ### Claims / ### Patterns / ### Correspondences / ### Contradictions headers,',
    'bullets starting with "- ", and a closing ``` after the last bullet. Do not forget it.',
  ].join('\n');
}
